#!/usr/bin/env bash
# scripts/download-textures.sh
# Downloads all unique texture PNGs from InventivetalentDev/minecraft-assets
# into public/textures/. Safe to re-run — skips existing files.

BASE_URL="https://raw.githubusercontent.com/InventivetalentDev/minecraft-assets/1.21/assets/minecraft/textures/block"
DEST="$(dirname "$0")/../public/textures"

mkdir -p "$DEST"

success=0
fail=0

download() {
  local file="$1"
  local dest="$DEST/$file"
  if [ -f "$dest" ]; then
    return
  fi
  if curl -sf -o "$dest" "$BASE_URL/$file"; then
    echo "OK  $file"
    ((success++))
  else
    echo "404 $file"
    rm -f "$dest"
    ((fail++))
  fi
}

# All unique texture filenames referenced in materials.js
download stone.png
download granite.png
download polished_granite.png
download diorite.png
download polished_diorite.png
download andesite.png
download polished_andesite.png
download cobblestone.png
download mossy_cobblestone.png
download stone_bricks.png
download mossy_stone_bricks.png
download cracked_stone_bricks.png
download chiseled_stone_bricks.png
download smooth_stone.png
download calcite.png
download tuff.png
download tuff_bricks.png
download polished_tuff.png
download chiseled_tuff.png
download deepslate_top.png
download cobbled_deepslate.png
download polished_deepslate.png
download deepslate_bricks.png
download cracked_deepslate_bricks.png
download deepslate_tiles.png
download cracked_deepslate_tiles.png
download chiseled_deepslate.png
download reinforced_deepslate.png
download dirt.png
download coarse_dirt.png
download rooted_dirt.png
download grass_block_top.png
download podzol_top.png
download mycelium_top.png
download mud.png
download packed_mud.png
download mud_bricks.png
download farmland.png
download dirt_path_top.png
download sand.png
download red_sand.png
download sandstone.png
download smooth_sandstone.png
download chiseled_sandstone.png
download cut_sandstone.png
download red_sandstone.png
download smooth_red_sandstone.png
download chiseled_red_sandstone.png
download cut_red_sandstone.png
download gravel.png
download bricks.png
download mossy_bricks.png
download chiseled_bricks.png
download oak_log.png
download oak_wood.png
download stripped_oak_log.png
download stripped_oak_wood.png
download oak_planks.png
download oak_leaves.png
download birch_log.png
download birch_wood.png
download stripped_birch_log.png
download stripped_birch_wood.png
download birch_planks.png
download birch_leaves.png
download spruce_log.png
download spruce_wood.png
download stripped_spruce_log.png
download stripped_spruce_wood.png
download spruce_planks.png
download spruce_leaves.png
download jungle_log.png
download jungle_wood.png
download stripped_jungle_log.png
download stripped_jungle_wood.png
download jungle_planks.png
download jungle_leaves.png
download acacia_log.png
download acacia_wood.png
download stripped_acacia_log.png
download stripped_acacia_wood.png
download acacia_planks.png
download acacia_leaves.png
download dark_oak_log.png
download dark_oak_wood.png
download stripped_dark_oak_log.png
download stripped_dark_oak_wood.png
download dark_oak_planks.png
download dark_oak_leaves.png
download mangrove_log.png
download mangrove_wood.png
download stripped_mangrove_log.png
download stripped_mangrove_wood.png
download mangrove_planks.png
download mangrove_leaves.png
download mangrove_roots_side.png
download muddy_mangrove_roots_side.png
download cherry_log.png
download cherry_wood.png
download stripped_cherry_log.png
download stripped_cherry_wood.png
download cherry_planks.png
download cherry_leaves.png
download bamboo_block_side.png
download stripped_bamboo_block_side.png
download bamboo_planks.png
download bamboo_mosaic.png
download coal_ore.png
download iron_ore.png
download gold_ore.png
download diamond_ore.png
download emerald_ore.png
download lapis_ore.png
download redstone_ore.png
download copper_ore.png
download deepslate_coal_ore.png
download deepslate_iron_ore.png
download deepslate_gold_ore.png
download deepslate_diamond_ore.png
download deepslate_emerald_ore.png
download deepslate_lapis_ore.png
download deepslate_redstone_ore.png
download deepslate_copper_ore.png
download iron_block.png
download gold_block.png
download diamond_block.png
download emerald_block.png
download lapis_block.png
download redstone_block.png
download coal_block.png
download raw_iron_block.png
download raw_gold_block.png
download raw_copper_block.png
download copper_block.png
download exposed_copper.png
download weathered_copper.png
download oxidized_copper.png
download cut_copper.png
download exposed_cut_copper.png
download weathered_cut_copper.png
download oxidized_cut_copper.png
download terracotta.png
download white_terracotta.png
download orange_terracotta.png
download magenta_terracotta.png
download light_blue_terracotta.png
download yellow_terracotta.png
download lime_terracotta.png
download pink_terracotta.png
download gray_terracotta.png
download light_gray_terracotta.png
download cyan_terracotta.png
download purple_terracotta.png
download blue_terracotta.png
download brown_terracotta.png
download green_terracotta.png
download red_terracotta.png
download black_terracotta.png
download white_glazed_terracotta.png
download orange_glazed_terracotta.png
download magenta_glazed_terracotta.png
download light_blue_glazed_terracotta.png
download yellow_glazed_terracotta.png
download lime_glazed_terracotta.png
download pink_glazed_terracotta.png
download gray_glazed_terracotta.png
download light_gray_glazed_terracotta.png
download cyan_glazed_terracotta.png
download purple_glazed_terracotta.png
download blue_glazed_terracotta.png
download brown_glazed_terracotta.png
download green_glazed_terracotta.png
download red_glazed_terracotta.png
download black_glazed_terracotta.png
download white_concrete.png
download orange_concrete.png
download magenta_concrete.png
download light_blue_concrete.png
download yellow_concrete.png
download lime_concrete.png
download pink_concrete.png
download gray_concrete.png
download light_gray_concrete.png
download cyan_concrete.png
download purple_concrete.png
download blue_concrete.png
download brown_concrete.png
download green_concrete.png
download red_concrete.png
download black_concrete.png
download white_concrete_powder.png
download orange_concrete_powder.png
download magenta_concrete_powder.png
download light_blue_concrete_powder.png
download yellow_concrete_powder.png
download lime_concrete_powder.png
download pink_concrete_powder.png
download gray_concrete_powder.png
download light_gray_concrete_powder.png
download cyan_concrete_powder.png
download purple_concrete_powder.png
download blue_concrete_powder.png
download brown_concrete_powder.png
download green_concrete_powder.png
download red_concrete_powder.png
download black_concrete_powder.png
download white_wool.png
download orange_wool.png
download magenta_wool.png
download light_blue_wool.png
download yellow_wool.png
download lime_wool.png
download pink_wool.png
download gray_wool.png
download light_gray_wool.png
download cyan_wool.png
download purple_wool.png
download blue_wool.png
download brown_wool.png
download green_wool.png
download red_wool.png
download black_wool.png
download glass.png
download tinted_glass.png
download white_stained_glass.png
download orange_stained_glass.png
download magenta_stained_glass.png
download light_blue_stained_glass.png
download yellow_stained_glass.png
download lime_stained_glass.png
download pink_stained_glass.png
download gray_stained_glass.png
download light_gray_stained_glass.png
download cyan_stained_glass.png
download purple_stained_glass.png
download blue_stained_glass.png
download brown_stained_glass.png
download green_stained_glass.png
download red_stained_glass.png
download black_stained_glass.png
download prismarine.png
download prismarine_bricks.png
download dark_prismarine.png
download sea_lantern.png
download ice.png
download packed_ice.png
download blue_ice.png
download snow.png
download cactus_side.png
download dead_bush.png
download vine.png
download lily_pad.png
download moss_block.png
download azalea_top.png
download flowering_azalea_top.png
download spore_blossom.png
download dripstone_block.png
download sculk.png
download sculk_catalyst_bottom.png
download sculk_sensor_bottom.png
download sculk_shrieker_bottom.png
download amethyst_block.png
download budding_amethyst.png
download dried_kelp_side.png
download sponge.png
download wet_sponge.png
download red_mushroom_block.png
download brown_mushroom_block.png
download mushroom_stem.png
download melon_side.png
download pumpkin_side.png
download carved_pumpkin.png
download jack_o_lantern.png
download hay_block_side.png
download honeycomb_block.png
download honey_block_top.png
download bone_block_side.png
download crafting_table_top.png
download furnace_front_off.png
download blast_furnace_front_off.png
download smoker_front_off.png
download barrel_top.png
download bookshelf.png
download chiseled_bookshelf.png
download enchanting_table_top.png
download anvil_top.png
download note_block.png
download jukebox_top.png
download tnt_side.png
download dispenser_front_horizontal.png
download dropper_front_horizontal.png
download observer_front.png
download piston_top_normal.png
download piston_top_sticky.png
download hopper_top.png
download beacon.png
download redstone_lamp.png
download target_top.png
download cartography_table_top.png
download fletching_table_top.png
download smithing_table_top.png
download loom_top.png
download composter_top.png
download stonecutter_top.png
download obsidian.png
download slime_block.png
download clay.png
download lodestone_top.png
download purpur_block.png
download purpur_pillar.png
download end_stone.png
download end_stone_bricks.png
download suspicious_sand_0.png
download suspicious_gravel_0.png
download netherrack.png
download soul_sand.png
download soul_soil.png
download glowstone.png
download magma.png
download ancient_debris_top.png
download crying_obsidian.png
download shroomlight.png
download nether_bricks.png
download red_nether_bricks.png
download cracked_nether_bricks.png
download chiseled_nether_bricks.png
download blackstone.png
download gilded_blackstone.png
download polished_blackstone.png
download polished_blackstone_bricks.png
download cracked_polished_blackstone_bricks.png
download chiseled_polished_blackstone.png
download basalt_side.png
download smooth_basalt.png
download polished_basalt_side.png
download crimson_stem.png
download stripped_crimson_stem.png
download crimson_hyphae.png
download stripped_crimson_hyphae.png
download crimson_planks.png
download crimson_nylium.png
download warped_stem.png
download stripped_warped_stem.png
download warped_hyphae.png
download stripped_warped_hyphae.png
download warped_planks.png
download warped_nylium.png
download crimson_fungus.png
download warped_fungus.png
download nether_wart_block.png
download warped_wart_block.png
download crimson_roots.png
download warped_roots.png
download nether_quartz_ore.png
download nether_gold_ore.png
download netherite_block.png
download quartz_block_side.png
download smooth_quartz.png
download quartz_bricks.png
download chiseled_quartz_block.png
download quartz_pillar.png
download respawn_anchor_top_off.png

echo ""
echo "Done. Downloaded: $success  Failed/skipped: $fail"
